// <auto-generated />
namespace MVCBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogPostIdaddedtoCommentposttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogPostIdaddedtoCommentposttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201709261202344_BlogPostId added to Commentpost table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
